@startuml
!include prelude.iuml

'skinparam defaultFontName Consolas

hide fields
hide methods

interface Signal <<TRAIT>> {
	value: T
	option: Option[T]
}

interface Immutable <<TRAIT>> extends Signal

class Constant <<CLASS>> extends Immutable
class Undefined <<OBJECT>> extends Immutable

interface Mutable <<TRAIT>> extends Signal

class Source <<CLASS>> extends Mutable

interface Child <<TRAIT>> extends Mutable

abstract class Expression <<CLASS>> extends Child

interface Deferred <<TRAIT>> extends Child
interface Lazy <<TRAIT>> extends Child

class DeferredExpression <<CLASS>> extends Expression, Deferred
class LazyExpression <<CLASS>> extends Expression, Lazy


@enduml
